"use client";

import { DataState, Empty, PageHeader, Panel, StatusBadge, useDashboard } from "../ui";

function Integration({ title, summary, status }) { return <Panel className="span-4" title={title} action={<StatusBadge tone={status === "ready" || status === "configured" ? "good" : "warn"}>{status}</StatusBadge>}><p className="muted">{summary}</p><button className="button ghost" type="button">Inspect contract →</button></Panel>; }

export default function IntegrationsPage() {
  const platform = useDashboard("platform", { mcpServers: [], plugins: [], render: { valid: false }, ecosystem: { counts: { total: 0, healthy: 0, attention: 0 } } });
  const clouds = useDashboard("clouds", { clouds: [] });
  const overview = platform.data ?? { mcpServers: [], plugins: [], render: { valid: false }, ecosystem: { counts: { total: 0, healthy: 0, attention: 0 } } };
  const cloudAdapters = clouds.data?.clouds ?? [];
  return <DataState loading={platform.loading || clouds.loading} error={platform.error || clouds.error}><PageHeader eyebrow="Core / integration fabric" title="Connect deliberately." description="MCP, plugins, deployment blueprints, cloud adapters, and ecosystem health are visible here with explicit boundaries for every external effect." action={<StatusBadge tone="warn">Consent-gated</StatusBadge>} /><div className="grid"><Integration title="MCP servers" summary={`${overview.mcpServers.length} registered. Activation stays disabled until explicit confirmation.`} status={overview.mcpServers.length ? "configured" : "empty"} /><Integration title="Plugins" summary={`${overview.plugins.length} installed records. Trust and enablement remain separate operations.`} status={overview.plugins.length ? "configured" : "empty"} /><Integration title="Render" summary={overview.render.valid ? "Blueprint structurally valid; deployment requires consent." : "No valid blueprint configured."} status={overview.render.valid ? "ready" : "review"} /></div><section className="section"><div className="section-heading"><div><h2>Cloud adapters</h2><p className="muted">Credential status and readiness only; no deployment is initiated here.</p></div></div><div className="grid">{cloudAdapters.map((cloud) => <Panel className="span-4" key={cloud.cloud ?? cloud.name} title={cloud.cloud ?? cloud.name} action={<StatusBadge tone={cloud.valid ? "good" : "warn"}>{cloud.valid ? "ready" : "not configured"}</StatusBadge>}><p className="muted">{cloud.message ?? cloud.reason ?? "Consent-gated adapter"}</p></Panel>)}</div></section><section className="section"><Panel title="Workspace ecosystem health" subtitle="Each signal is independent; no composite security score is implied."><div className="grid"><div className="span-4"><p className="metric-value">{overview.ecosystem.counts.total}</p><p className="muted">checks inspected</p></div><div className="span-4"><p className="metric-value">{overview.ecosystem.counts.healthy}</p><p className="muted">healthy signals</p></div><div className="span-4"><p className="metric-value">{overview.ecosystem.counts.attention}</p><p className="muted">signals needing review</p></div></div></Panel></section></DataState>;
}
