"use client";

import { useMemo } from "react";
import { DataState, PageHeader, Panel, StatusBadge, useDashboard } from "../ui";

export default function SecurityPage() {
  const view = useDashboard("providers");
  const evidence = useMemo(() => (view.data?.compatibility ?? []).map(([provider, record]) => ({ provider, ...(record ?? {}) })), [view.data]);
  return <DataState loading={view.loading} error={view.error}><PageHeader eyebrow="Trust / evidence" title="Security you can inspect." description="Forgevena keeps trust evidence dimensional: provenance, freshness, vulnerability state, evaluation coverage, publisher identity, and support are not collapsed into a deceptive score." action={<StatusBadge tone="good">No telemetry by default</StatusBadge>} /><div className="grid"><Panel className="span-4" title="Secret handling"><p className="metric-value">Local</p><p className="muted">Masked input only. Credential values stay in provider-specific ignored storage and never enter registry metadata, logs, or this UI.</p></Panel><Panel className="span-4" title="External effects"><p className="metric-value">Gated</p><p className="muted">Provider tests, MCP activation, deployment, billing, and publication require explicit consent and normalized evidence.</p></Panel><Panel className="span-4" title="Human authority"><p className="metric-value">Required</p><p className="muted">Agents and workflows can recommend and plan; promotion, mutation, release, and credential use remain human-controlled.</p></Panel></div><section className="section"><div className="section-heading"><div><h2>Compatibility evidence</h2><p className="muted">Dated local metadata only. Missing evidence is visible and actionable.</p></div></div><Panel><div className="list">{evidence.map((record) => <div className="list-item" key={record.provider}><div className="list-copy"><strong>{record.provider}</strong><span>Evidence {record.evidenceId ?? "not recorded"} · last verified {record.lastVerifiedAt ?? "not verified"}</span></div><StatusBadge tone={record.freshness === "fresh" ? "good" : "warn"}>{record.freshness ?? "unverified"}</StatusBadge></div>)}</div></Panel></section><section className="section"><div className="grid"><Panel className="span-6" title="Trust boundaries"><div className="list">{["Browser tab → authenticated loopback session", "Dashboard → normalized domain services", "Provider adapter → external service only after consent", "Agent host → compatibility-only integration", "Registry → package trust and evidence authority"].map((item) => <div className="list-item" key={item}><div className="list-copy"><strong>{item}</strong></div><StatusBadge tone="good">Declared</StatusBadge></div>)}</div></Panel><Panel className="span-6" title="Operational response"><p className="muted">When evidence is stale, a provider fails, or a credential is quarantined, use the canonical provider platform runbook. Preserve operation IDs and normalized error codes only—never copy prompts, responses, credentials, or authorization headers into incidents.</p><a className="button" href="https://rohitkumarnaidu.github.io/Forgevena/" target="_blank" rel="noreferrer">Open documentation ↗</a></Panel></div></section></DataState>;
}
