"use client";

import { useState } from "react";
import { clearDashboardSession, connectDashboardUrl, sessionToken } from "../../api-client";
import { PageHeader, Panel, StatusBadge } from "../ui";

export default function SettingsPage() {
  const [url, setUrl] = useState("");
  const [message, setMessage] = useState("");
  const [tokenPresent, setTokenPresent] = useState(Boolean(sessionToken()));
  function connect(event) { event.preventDefault(); try { connectDashboardUrl(url); setTokenPresent(true); setMessage("Connected for this browser session. Reload a workspace page to fetch data."); } catch (error) { setMessage(error.message); } }
  function clear() { clearDashboardSession(); setTokenPresent(false); setMessage("Session cleared. Stored provider keys were not changed."); }
  return <><PageHeader eyebrow="Console / settings" title="Make the console yours." description="Manage this browser session, theme preference, and local API bridge. Product data and credentials remain owned by the Forgevena workspace." action={<StatusBadge tone={tokenPresent ? "good" : "warn"}>{tokenPresent ? "Session active" : "Not connected"}</StatusBadge>} /><div className="grid"><Panel className="span-7" title="Loopback connection" subtitle="The Next.js bridge forwards only allowlisted routes to the local Forgevena server."><form className="stack-form" onSubmit={connect}><label className="field-label">Dashboard URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="http://127.0.0.1:4317/#token=…" required /></label><div className="button-row"><button className="button primary" type="submit">Connect session</button><button className="button" type="button" onClick={clear}>Clear session</button></div>{message && <p className="muted">{message}</p>}</form></Panel><Panel className="span-5" title="Privacy posture"><div className="list"><div className="list-item"><div className="list-copy"><strong>Session token</strong><span>Browser session storage only</span></div><StatusBadge tone="good">Private</StatusBadge></div><div className="list-item"><div className="list-copy"><strong>Telemetry</strong><span>No behavioral analytics</span></div><StatusBadge tone="good">Off</StatusBadge></div><div className="list-item"><div className="list-copy"><strong>Theme</strong><span>Stored in this browser only</span></div><StatusBadge tone="good">Local</StatusBadge></div></div></Panel></div><section className="section"><div className="grid"><Panel className="span-6" title="Operator preferences"><p className="muted">Use the sun/moon control in the top bar to switch between dark and light themes. The console defaults to dark mode and honors reduced-motion preferences.</p></Panel><Panel className="span-6" title="Runtime boundary"><p className="muted">This app is a presentation layer. Forgevena Core remains the authority for policy, credentials, workflows, rollback, audit, and consent. The Next.js app cannot run arbitrary workflows.</p></Panel></div></section></>;
}
