const cloudCredentialPlaceholders = ["VERCEL_TOKEN", "RAILWAY_TOKEN", "FLY_API_TOKEN", "AZURE_CLIENT_SECRET", "AWS_SECRET_ACCESS_KEY", "GOOGLE_APPLICATION_CREDENTIALS", "DIGITALOCEAN_ACCESS_TOKEN"];
const file = (relative, contents) => {
  let normalized = contents.trim();
  if (relative === ".gitignore" && !normalized.includes(".credentials/")) normalized += "\n.credentials/";
  if (relative === ".env.example") for (const variable of cloudCredentialPlaceholders) if (!normalized.includes(`${variable}=`)) normalized += `\n${variable}=`;
  return { relative, contents: `${normalized}\n` };
};

export function moduleFiles(moduleName) {
  switch (moduleName) {
    case "core": return [file(".ai-workspace/README.md", "# AI Workspace State\n\nThis directory contains project-scoped configuration, registry data, logs, and backups. Do not commit secrets.")];
    case "doctor": return [];
    case "registry": return [];
    case "logging": return [];
    case "config": return [file("configs/README.md", "# Configuration\n\nProject configuration inherits platform defaults and may be overridden by approved environment variables.")];
    case "templates": return [file("templates/README.md", "# Templates\n\nUse versioned project, documentation, configuration, and prompt templates. Existing files are never overwritten.")];
    case "providers": return [file("providers/README.md", "# Provider Adapters\n\nProvider adapters are capability declarations only in Phase 2. They do not install or configure external AI products.")];
    case "project": return [file(".ai/README.md", "# AI Project Context\n\nKeep provider-neutral, non-secret project context here.")];
    case "bootstrap": return [file("README.md", "# Project\n\n## Overview\n\nDescribe the product, local setup, validation, and ownership."), file(".gitignore", ".env\n.env.*\n!.env.example\nnode_modules/\n.venv/\n__pycache__/\n.ai-workspace/local-secrets/\n.ai-workspace/logs/\n.ai-workspace/backups/\n"), file(".gitattributes", "* text=auto eol=lf\n"), file(".editorconfig", "root = true\n\n[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\nindent_style = space\nindent_size = 2\n"), file("CONTRIBUTING.md", "# Contributing\n\nUse focused changes, tests, and documented decisions. Follow conventional commits.\n"), file("SECURITY.md", "# Security Policy\n\nReport vulnerabilities privately. Never commit secrets.\n"), file(".env.example", "# Copy only the variables you need into an approved local secret store.\nOPENAI_API_KEY=\nANTHROPIC_API_KEY=\nGEMINI_API_KEY=\nOPENROUTER_API_KEY=\nCURSOR_API_KEY=\nRENDER_API_KEY=\n"), file("src/README.md", "# Source\n\nApplication source belongs here.\n"), file("assets/README.md", "# Assets\n\nStatic project assets.\n"), file("examples/README.md", "# Examples\n\nRunnable examples and usage demonstrations.\n"), file("scripts/README.md", "# Scripts\n\nNon-secret local development and automation scripts.\n"), file("docker/README.md", "# Docker\n\nDevelopment and production container definitions.\n"), file("monitoring/README.md", "# Monitoring\n\nHealth, metrics, logs, and tracing configuration.\n"), file("security/README.md", "# Security\n\nSecurity policies, dependency controls, and threat-model artifacts.\n")];
    case "openspec": return [file("docs/OPEN_SPEC_WORKFLOW.md", "# OpenSpec Workflow\n\nInstall the official CLI globally, review `openspec init --help`, then run `openspec init` manually in this repository. Use `/opsx:propose` before implementation, `/opsx:apply` for approved tasks, and `/opsx:archive` when complete.")];
    case "design": return [file("DESIGN.md", "# Design System\n\n## Principles\n- Accessible, responsive, purposeful, and consistent.\n- Use semantic design tokens; avoid arbitrary visual values.\n\n## Foundations\nDefine color tokens for light and dark modes, typography scale, spacing scale, responsive grid, elevation, motion, and iconography before implementation.\n\n## Components\nDocument states, variants, focus behavior, empty/loading/error states, and accessibility requirements for every reusable component.\n\n## Accessibility\nMeet WCAG 2.2 AA contrast and keyboard-navigation expectations. Respect reduced-motion preferences.")];
    case "docs": return [file("docs/ARCHITECTURE.md", "# Architecture\n\nDocument system context, components, data flows, trust boundaries, and key architectural decisions."), file("docs/architecture/README.md", "# Architecture\n\nSystem context, component, and data-flow documentation."), file("docs/adr/README.md", "# Architecture Decision Records\n\nCreate one immutable ADR per material decision."), file("docs/api/README.md", "# API\n\nContracts, versioning, authentication, and error conventions."), file("docs/database/README.md", "# Database\n\nData ownership, migrations, retention, backups, and recovery."), file("docs/security/README.md", "# Security\n\nThreat model, secrets, authentication, authorization, and vulnerability handling."), file("docs/testing/README.md", "# Testing\n\nTest strategy, commands, coverage, and release evidence."), file("docs/deployment/README.md", "# Deployment\n\nEnvironments, releases, rollback, and ownership."), file("docs/operations/README.md", "# Operations\n\nMonitoring, alerts, incident ownership, and service objectives."), file("docs/runbooks/README.md", "# Runbooks\n\nRepeatable operating procedures and incident response."), file("docs/decisions/README.md", "# Decisions\n\nDecision records and links to approved ADRs."), file("docs/DEVELOPMENT.md", "# Development Guide\n\nRecord prerequisites, local commands, test commands, and release checks."), file("docs/CODING_STANDARDS.md", "# Coding Standards\n\nUse tested, maintainable, secure, readable changes with documented decisions."), file("docs/TROUBLESHOOTING.md", "# Troubleshooting\n\nRecord symptoms, diagnostics, safe fixes, and escalation paths."), file("docs/PROJECT_LIFECYCLE.md", "# Project Lifecycle\n\nRequirements, design, implementation, validation, release, and operation."), file("docs/BRANCHING_AND_VERSIONING.md", "# Branching and Versioning\n\nUse protected mainline branches, conventional commits, and semantic versioning."), file("docs/SECURITY.md", "# Security\n\nDocument assets, trust boundaries, secrets handling, authentication, authorization, and vulnerability reporting."), file("docs/DEPLOYMENT.md", "# Deployment\n\nDocument environments, required configuration, release process, rollback process, and operational ownership.")];
    case "github": return [file(".github/workflows/README.md", "# CI Workflows\n\nStack templates add reviewed lint, test, build, and dependency-scan workflows. Add application release workflows after deployment approval."), file(".github/pull_request_template.md", "# Summary\n\n## Validation\n\n## Risks\n")];
    case "testing": return [file("docs/TESTING.md", "# Testing Strategy\n\nDefine unit, integration, end-to-end, security, regression, coverage thresholds, and release evidence."), file("tests/unit/README.md", "# Unit Tests\n"), file("tests/integration/README.md", "# Integration Tests\n"), file("tests/e2e/README.md", "# End-to-End Tests\n"), file("tests/README.md", "# Tests\n\nKeep automated tests close to the applicable application code or document their location here.")];
    case "docker": return [file("docs/CONTAINERIZATION.md", "# Containerization\n\nStack templates provide Docker assets where a runtime is known. Record a deployment decision before adding runtime-specific files to a blank or enterprise template.")];
    case "monitoring": return [file("docs/OBSERVABILITY.md", "# Observability\n\nDefine structured logs, metrics, traces, alerts, retention, dashboards, and ownership before production deployment."), file("monitoring/healthcheck.md", "# Health Checks\n\nDefine liveness, readiness, metrics, tracing, and alert ownership before release.")];
    case "ai": return [file(".ai/README.md", "# AI Project Context\n\nKeep provider-specific, non-secret project context here. Do not store API keys, tokens, production data, or memory shared with unrelated projects."), file("prompts/README.md", "# Prompts\n\nStore reusable, reviewed project prompts here."), file("templates/README.md", "# Project Templates\n\nStore project-local document and code templates here."), file("configs/README.md", "# Configuration\n\nStore non-secret AI workspace configuration here. Use untracked environment files or a secret manager for credentials.")];
    default: throw new Error(`Unsupported module: ${moduleName}`);
  }
}
